create table if not exists public.processed_messages (
  message_id text primary key,
  from_number text not null,
  received_at timestamptz not null default now()
);

create table if not exists public.pending_records (
  from_number text primary key,
  record_json jsonb not null,
  original_message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.records (
  id bigint generated by default as identity primary key,
  record_type text not null check (record_type in ('OFFER', 'DEMAND')),
  operation text check (operation is null or operation in ('SALE', 'RENT')),
  property_type text,
  zones jsonb not null default '[]'::jsonb,
  price_min numeric,
  price_max numeric,
  currency text not null default 'MXN',
  area_min_m2 numeric,
  area_max_m2 numeric,
  bedrooms_min numeric,
  bathrooms_min numeric,
  parking_min numeric,
  features jsonb not null default '[]'::jsonb,
  source_contact text,
  source_group text,
  original_message text not null,
  status text not null default 'ACTIVE' check (status in ('PENDING_CONFIRMATION', 'ACTIVE', 'EXPIRED', 'CLOSED', 'DISCARDED')),
  confidence numeric not null default 0 check (confidence >= 0 and confidence <= 1),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  confirmed_at timestamptz not null default now()
);

create index if not exists records_active_expiry_idx on public.records (status, expires_at);
create index if not exists records_type_status_idx on public.records (record_type, status);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  offer_id bigint not null references public.records(id) on delete cascade,
  demand_id bigint not null references public.records(id) on delete cascade,
  score numeric not null check (score >= 0 and score <= 100),
  reasons jsonb not null default '[]'::jsonb,
  status text not null default 'NEW' check (status in ('NEW', 'ALERTED', 'REVIEWED', 'DISCARDED')),
  alerted_at timestamptz,
  created_at timestamptz not null default now(),
  unique (offer_id, demand_id)
);

alter table public.processed_messages enable row level security;
alter table public.pending_records enable row level security;
alter table public.records enable row level security;
alter table public.matches enable row level security;

revoke all on public.processed_messages from anon, authenticated;
revoke all on public.pending_records from anon, authenticated;
revoke all on public.records from anon, authenticated;
revoke all on public.matches from anon, authenticated;
